blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:article_id>', views.detail, name='detail'),
    path('edit/<int:article_id>', views.edit, name='edit'),
    path('delete/<int:article_id>', views.delete, name='delete'),
]

loginApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('blog.urls')),  # Redirige la raíz a la app "blog"
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),  # Añadido
]

templates/base.html
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
  </head>
  <body>
    <nav>
      <ul>
        <!-- Aquí comienza -->
        {% if user.is_authenticated %}
        <li><a href="{% url 'blog:index' %}">Blog List</a></li>
        <li><a href="{% url 'logout' %}">Cerrar Sesion</a></li>
        <li><a href="{% url 'user_detail' user.pk %}">Información del usuario</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Iniciar Sesion</a></li>
        <li><a href="{% url 'signup' %}">Registrar Usuario</a></li>
        {% endif %}
        <!-- Aquí termina -->
      </ul>
    </nav>
    <main>
      <div>
        {% block main %}
        {% endblock %}
      </div>
    </main>
  </body>
</html>